[package]
name = "GH"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
ark-ff = "0.5.0"
ark-crypto-primitives = { version = "0.5", features = ["merkle_tree"] }
ark-std = "0.5.0"
ark-poly = "0.5.0"
